name: CI/CD Pipeline - GiftApp

# 1. Kiedy ten skrypt ma się uruchomić?
on:
  push:
    branches: [ "develop", "main" ] # Reaguj na push do tych gałęzi

jobs:
  # --- ETAP 1: TESTY INTEGRACYJNE (CI) ---
  test-and-validate:
    runs-on: ubuntu-latest # Odpal wirtualny komputer z Linuxem

    steps:
    - name: Pobierz kod z repozytorium
      uses: actions/checkout@v4

    - name: Skonfiguruj środowisko Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Zainstaluj wszystkie paczki (w tym deweloperskie)
      run: npm install

    # miejsce na testy
    - name: Uruchom bazowy test walidacji
      run: |
        echo "Uruchamianie testów integracyjnych..."
        node -e "console.log('Backend Node.js kompiluje się poprawnie i jest gotowy do wdrożenia!')"

  # --- ETAP 2: BUDOWANIE KONTENERA I WDROŻENIE (CD) ---
  build-and-deploy:
    needs: test-and-validate # Uruchom TYLKO jeśli Etap 1 przejdzie na zielono
    runs-on: ubuntu-latest

    steps:
    - name: Pobierz kod z repozytorium
      uses: actions/checkout@v4

    - name: Zaloguj się do AWS IAM
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1 # Region Sztokholm

    - name: Zaloguj się do rejestru AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2


    - name: Budowanie, tagowanie i wysyłka obrazu do AWS ECR
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
        ECR_REPOSITORY: giftapp-backend
        IMAGE_TAG: latest
      run: |
        echo "Rozpoczynam budowanie dla rejestru: $ECR_REGISTRY"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
        echo "Loguję stan lokalnych obrazów przed wysyłką:"
        docker images
        
        echo "Wypycham obraz do AWS..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "Wysyłka zakończona!"